### ISSUE TITLE
Looking at any block in the game will show an error

### ISSUE THREAD

**Issue by XiaoHuiHui233** [badasintended/wthit#108]
### Describe the issue

Just randomly enter a world and look at any block will show an error message. Check out the following files:
```
2022-02-07 - 20:44:33
class bre2el.uti.compat.waila.HUDHandlerBlocksLocal
java.lang.NoSuchFieldError: config
	at bre2el.uti.compat.waila.HUDHandlerBlocksLocal.appendHead(HUDHandlerBlocksLocal.java:43)
	at mcp.mobius.waila.api.IComponentProvider.appendHead(IComponentProvider.java:23)
	at mcp.mobius.waila.hud.ComponentHandler.handleBlock(ComponentHandler.java:61)
	at mcp.mobius.waila.hud.ComponentHandler.gatherBlock(ComponentHandler.java:49)
	at mcp.mobius.waila.hud.ClientTickHandler.tick(ClientTickHandler.java:86)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:44)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:20)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$cfi000$onEndTick(class_310.java:7497)
	at net.minecraft.class_310.method_1574(class_310.java:1807)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Game version: 1.18.1
Fabric loader version: 0.13.1
Fabric API version: 0.46.4
Plugins: (The test without the plugins still reports an error)
- breakprogress-1.0.1
- can-i-mine-this-block-1.1.0

Tried deleting the config folder but to no avail. Didn't try to test conflict between mods, but this shouldn't happen. I can provide mods list if needed.

### Log output

https://gist.github.com/XiaoHuiHui233/767dab653363c1486033d3cd86bec9f8

**Comment by deirn** [comment]
Can you post your full log?

**Comment by XiaoHuiHui233** [comment]
Of course, I uploaded the `latest.log` file in the link below.
https://gist.github.com/XiaoHuiHui233/75ab90ab372d477ef482147802b12979

**Comment by deirn** [comment]
It seems to be caused by [Untranslated Items](https://www.curseforge.com/minecraft/mc-mods/untranslated-items) touching WTHIT's unsupported internals. I suggest opening an issue there.

It seems like it has an option to disable the compatibility, try setting `dispBothLanguagesOnWaila` to false on its config.
