### ISSUE TITLE
Insane lag when looking at a bedrock users pet in java

### ISSUE THREAD

**Issue by Shurayukii** [badasintended/wthit#113]
### Describe the issue

using "Geyser" on a Minecraft server (allows bedrock users to join on java) and looking at a bedrock users pet makes u go to 0 fps while I normally run at 75-85 fps with mods and shaders

### Log output

https://gist.github.com/Shurayukii/7d93f1f2b3d04983bb161847c555b243

### Additional context

a video showing off the bug on a parrot: https://www.youtube.com/watch?v=uD2U6WHFebk

**Comment by deirn** [comment]
Can you send me your `waila_errors.log`?

**Comment by Shurayukii** [comment]
> 

this is basically my error log:

2022-02-27 - 16:53:54
class mcp.mobius.waila.plugin.vanilla.provider.PetOwnerProvider
java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187)
	at mcp.mobius.waila.plugin.vanilla.provider.PetOwnerProvider.appendBody(PetOwnerProvider.java:48)
	at mcp.mobius.waila.hud.ComponentHandler.gatherEntity(ComponentHandler.java:103)
	at mcp.mobius.waila.hud.ClientTickHandler.tick(ClientTickHandler.java:119)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:44)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:20)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zfl000$onEndTick(class_310.java:5997)
	at net.minecraft.class_310.method_1574(class_310.java:1807)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by deirn** [comment]
Hmm sounds like the same underlying issue as #109, closing this as duplicate.

You can disable the pet owner tooltip on the minecraft plugin for the time being.
