### ISSUE TITLE
Hello, I have a question, I use loader 0.13.3 and I get a crashed, do you know how I can solve it?

### ISSUE THREAD

**Issue by Artiverius** [badasintended/wthit#127]
### Describe the issue

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
Código de error: -1

### Log output

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalArgumentException: No enum constant mcp.mobius.waila.plugin.vanilla.config.Options.NoteDisplayMode.false
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at mcp.mobius.waila.config.ConfigEntry.lambda$static$4(ConfigEntry.java:14)
	at mcp.mobius.waila.config.PluginConfig.lambda$reload$3(PluginConfig.java:129)
	at java.base/java.util.Map.forEach(Map.java:713)
	at mcp.mobius.waila.config.PluginConfig.lambda$reload$4(PluginConfig.java:126)
	at java.base/java.util.Map.forEach(Map.java:713)
	at mcp.mobius.waila.config.PluginConfig.reload(PluginConfig.java:126)
	at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:30)
	at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:44)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

### Additional context

I use fabric 1.18.2 with loader 0.13.3 and I have problems to enter with the Wthit mod

**Comment by deirn** [comment]
That doesn't say anything, post the entire log as a   [gist](https://gist.github.com) and send the link here.

**Comment by Artiverius** [comment]
Modify what I wrote, is the new information useful to you?

**Comment by deirn** [comment]
Delete the plugin config file at `.minecraft/config/waila/waila_plugins.json`.

**Comment by Artiverius** [comment]
Thank you very much, the mod is already working
