### ISSUE TITLE
[Forge 1.18.1] Error creating instance of plugin null (startup)

### ISSUE THREAD

**Issue by skies912** [badasintended/wthit#136]
### Describe the issue

Forge 39.1.0
WTHIT 4.5.5

During startup, I am experiencing a non critical but consistent error from this mod. Mod still works as intended but am in process of cleaning runtime errors.

Here's a snippet:
`[10:20:59] [Worker-Main-14/ERROR]: [WTHIT] Error creating instance of plugin null
java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.resources.ResourceLocation.m_135832_(ResourceLocation.java:84) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:55) ~[client-1.18.1-20211210.034407-srg.jar%23236!/:?]
	at mcp.mobius.waila.plugin.PluginInfo.register(PluginInfo.java:43) ~[wthit-forge-4.5.5.jar%23231!/:4.5.5]
	at mcp.mobius.waila.forge.ForgePluginLoader.gatherPlugins(ForgePluginLoader.java:42) ~[wthit-forge-4.5.5.jar%23231!/:4.5.5]
	at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:18) ~[wthit-forge-4.5.5.jar%23231!/:4.5.5]
	at mcp.mobius.waila.forge.ForgeWaila.loadComplete(ForgeWaila.java:42) ~[wthit-forge-4.5.5.jar%23231!/:4.5.5]
	at net.minecraftforge.eventbus.ASMEventHandler_229_ForgeWaila_loadComplete_FMLLoadCompleteEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2337!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2337!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2337!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.1.0.jar%23238!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.1.0.jar%23237!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]`

If this has been fixed, feel free to close...

### Log output

https://gist.github.com/skies912/db3f82a5f1ac4c24d1e9a1223adf3b0b

**Comment by Trampa3** [comment]
[Server] ERROR [WTHIT]: [WTHIT] Error creating instance of plugin null
mismo error
