### ISSUE TITLE
Incompatible mod set!

### ISSUE THREAD

**Issue by ComputerJock** [badasintended/wthit#142]
### Describe the issue

For 1.18.2 I'm now getting:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install badpackets, version 0.1.2 or later.
Unmet dependency listing:
	 - Mod 'wthit' (wthit) 4.10.3 requires version 0.1.2 or later of badpackets, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

Here are my mods:
autoconfig1u-3.4.0 (1.18).jar
badpackets-fabric-0.1.2 (1.18+).jar
beenfo-1.18.2-fabric0.47.10-1.3.3.jar
BetterF3-1.2.5-Fabric-1.18.2.jar
cloth-config-6.2.62-fabric (1.18).jar
entityculling-fabric-mc1.18-1.5.1.jar
fabric-api-0.56.0+1.18.2.jar
fabric-carpet-1.18.2-1.4.69+v220331.jar
ferritecore-4.2.1-fabric (1.18).jar
iris-mc1.18.2-1.2.5.jar
litematica-fabric-1.18.2-0.11.3.jar
lithium-fabric-mc1.18.2-0.7.10.jar
malilib-fabric-1.18.2-0.12.1.jar
minihud-fabric-1.18.2-0.22.0.jar
modmenu-3.2.2 (1.18).jar
MouseTweaks-fabric-mc1.18-2.22.jar
NoFog-1.2.2_1.16.5-1.18.2-fabric.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
starlight-1.0.2+fabric.89b8d9f (1.18).jar
tweakeroo-fabric-1.18.2-0.13.3.jar
voxelmap-1.18.2-1.11.2.jar
WI-Zoom-1.3-MC1.18.2.jar
worldedit-mod-7.2.10 (1.18).jar
WorldEditCUI-1.18.2+01.jar
wthit-fabric-4.10.3 (1.18).jar

I'm using MultiMC
Fabric loader version 0.14.6

I've downloaded the most recent badpackets and wthit.

### Log output

https://gist.github.com/ComputerJock/1ae6d5d58a69ddee939a8cb00342db80

**Comment by ComputerJock** [comment]
I don't know what happened. I relaunched and the game now runs with wthit working properly. Sorry for the noise.
