### ISSUE TITLE
1.18.2: IllegalStateException (preconditions.checkState)

### ISSUE THREAD

**Issue by Geethebluesky** [badasintended/wthit#157]
### Describe the issue

Hello! I was doing literally nothing in my world (in the overworld) except looking into the distance, then suddenly this crash happened. The log has more but it's just different presentations of what's below.

I'm on WTHIT version: **wthit-fabric-4.13.0.jar**
Also using **wthit-plugins-1.0.6+1.18.2.jar** if that matters.

```
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at mcp.mobius.waila.gui.hud.Line.assertDimension(Line.java:105)
	at mcp.mobius.waila.gui.hud.Line.getWidth(Line.java:66)
	at mcp.mobius.waila.gui.hud.TooltipRenderer.endBuild(TooltipRenderer.java:124)
	at mcp.mobius.waila.gui.hud.TooltipHandler.tick(TooltipHandler.java:186)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:46)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:22)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$coh000$onEndTick(class_310.java:10972)
	at net.minecraft.class_310.method_1574(class_310.java:1817)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
```

### Log output and crash report

https://pastebin.com/Mb0vePct  (latest.log)

https://pastebin.com/qpgpQ3H5 (PolyMC log output)

### Additional context

I haven't had the chance to play in a few weeks and you updated WTHIT a few times I think. I can't really say if this is caused by a recent update or not, sorry.

**Comment by DadoIrie** [comment]
https://mclo.gs/oYe6fGO
looks pretty much like the same error I'm getting too

**Comment by deirn** [comment]
Can you try this <https://github.com/badasintended/wthit/suites/7878788841/artifacts/334417479>, use the jar inside `fabric/build/libs` without `api` or `source` suffix.

**Comment by deirn** [comment]
Confirmed by AOF team that the commit fixed it.
