### ISSUE TITLE
error on 1.18.2 in server console

### ISSUE THREAD

**Issue by Jannik44** [badasintended/wthit#185]
### Describe the issue

Hello this issue is maybe not important everything works as expected, anyways, found this error in the server console so it might be interesting to fix this for the upcoming versions

### Log output and crash report

[16:44:53] [modloading-worker-0/ERROR] [WTHIT/]: [WTHIT] Error creating instance of plugin null java.lang.NoClassDefFoundError: mcp/mobius/waila/api/ui/IElement 	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin} 	at java.lang.Class.forName(Class.java:375) ~[?:?] {re:mixin} 	at mcp.mobius.waila.plugin.PluginInfo.register(PluginInfo.java:42) ~[wthit-forge-4.13.5.jar%2394!/:4.13.5] {re:classloading} 	at mcp.mobius.waila.forge.ForgePluginLoader.gatherPlugins(ForgePluginLoader.java:42) ~[wthit-forge-4.13.5.jar%2394!/:4.13.5] {re:classloading} 	at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:18) ~[wthit-forge-4.13.5.jar%2394!/:4.13.5] {re:classloading} 	at mcp.mobius.waila.forge.ForgeWaila.loadComplete(ForgeWaila.java:41) ~[wthit-forge-4.13.5.jar%2394!/:4.13.5] {re:classloading,pl:eventbus:A} 	at net.minecraftforge.eventbus.ASMEventHandler_201_ForgeWaila_loadComplete_FMLLoadCompleteEvent.invoke(.dynamic) ~[?:?] {} 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {} 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.0.jar%23104!/:?] {} 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.0.jar%23103!/:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {} 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {} 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {} 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {} 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames} 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames} 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {} Caused by: java.lang.ClassNotFoundException: mcp.mobius.waila.api.ui.IElement 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {} 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {} 	... 19 more

**Comment by deirn** [comment]
You appear to have mods with jade plugin. You can ignore those errors.
