### ISSUE TITLE
Error in Server Log

### ISSUE THREAD

**Issue by ZtormTheCat** [badasintended/wthit#186]
### Describe the issue

I get an Error with a MI Plugin when starting my 1.19.2 Fabric Server

I'm not sure if this error is caused by a bug in megane, MI or WTHIT but, looking at the root of the Error I would guess WTHIT

### Log output and crash report

```
[main/ERROR]:[WTHIT] Error creating instance of plugin modern_industrialization:plugin
--
208 | java.lang.RuntimeException: Cannot load class aztech.modern_industrialization.compat.waila.MIWailaPlugin in environment type SERVER
209 | at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.13.jar:?]
210 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.13.jar:?]
211 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.13.jar:?]
212 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
213 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
214 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
215 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
216 | at java.lang.Class.forName0(Native Method) ~[?:?]
217 | at java.lang.Class.forName(Unknown Source) ~[?:?]
218 | at mcp.mobius.waila.plugin.PluginInfo.register(PluginInfo.java:52) ~[wthit-fabric-5.13.4.jar:?]
219 | at mcp.mobius.waila.fabric.FabricPluginLoader.gatherPlugins(FabricPluginLoader.java:100) ~[wthit-fabric-5.13.4.jar:?]
220 | at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:81) ~[wthit-fabric-5.13.4.jar:?]
221 | at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:47) ~[wthit-fabric-5.13.4.jar:?]
222 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.14.13.jar:?]
223 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.14.13.jar:?]
224 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) [fabric-loader-0.14.13.jar:?]
225 | at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
226 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.13.jar:?]
227 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.13.jar:?]
228 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.13.jar:?]
229 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.13.jar:?]
```

**Comment by deirn** [comment]
https://github.com/AztechMC/Modern-Industrialization/issues/441
