### ISSUE TITLE
Server-side crash on Minecraft 1.20.1 with WTHIT version 8.4.2 - doesn't crash on 8.4.1

### ISSUE THREAD

**Issue by evonzee** [badasintended/wthit#241]
### Describe the issue

Updated my 1.20.1 server to the latest versions of all our mods today, and the server won't start.  Downgrading wthit to 8.4.1 and making no other changes allows the server to start normally.

I think the problem must be a conflict with one of these mods (or perhaps with running in server mode altogether?) because I don't get the same crash when I run in client mode without these server-only mods:

- fabricproxy-lite
- huskhomes
- luckperms
- servux

I run under docker compose with itzg/minecraft-server.  I'll work on a minimal reproduction case and will post an update if I find anything interesting.

### Log output and crash report

https://gist.github.com/evonzee/46c127abde7273fc80e1e49846fb067d

**Comment by evonzee** [comment]
Looks like it doesn't have anything to do with conflicts with other mods.  A minimal test case with just WTHIT installed and no other mods still crashes:

docker-compose.yaml:
```
version: '3.7'

services:
  wthit:
    image: itzg/minecraft-server
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - VERSION=1.20.1
      - MAX_MEMORY=2G
      - MODRINTH_DOWNLOAD_DEPENDENCIES=required
      - MODRINTH_PROJECTS=wthit
```

Output:
```
[+] Building 0.0s (0/0)                                                                                                                                                                                                                                   docker:default
[+] Running 1/1
 ✔ Container server-config-wthit-1  Recreated                                                                                                                                                                                                                      10.3s 
Attaching to wthit-1
wthit-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 9 1000 1000 4096 Nov 21 18:15 /data'
wthit-1  | [init] Resolving type given FABRIC
wthit-1  | [mc-image-helper] 18:18:08.734 INFO  : Fabric launcher for minecraft 1.20.1 loader 0.14.24 is already available
wthit-1  | [mc-image-helper] 18:18:10.658 INFO  : Downloading wthit-fabric-8.4.2.jar
wthit-1  | [mc-image-helper] 18:18:10.726 INFO  : Downloading fabric-api-0.90.7+1.20.1.jar
wthit-1  | [mc-image-helper] 18:18:10.809 INFO  : Downloading badpackets-fabric-0.4.3.jar
wthit-1  | [mc-image-helper] 18:18:13.082 INFO  : Created/updated 1 property in /data/server.properties
wthit-1  | [init] Setting initial memory to 1G and max to 2G
wthit-1  | [init] Starting the Minecraft server...
wthit-1  | Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
wthit-1  | [18:18:18] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.24
wthit-1  | [18:18:18] [main/INFO]: Loading 44 mods:
wthit-1  |      - badpackets 0.4.3
wthit-1  |      - fabric-api 0.90.7+1.20.1
wthit-1  |         |-- fabric-api-base 0.4.30+7abfd51577
wthit-1  |         |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
wthit-1  |         |-- fabric-biome-api-v1 13.0.12+215bbe9677
wthit-1  |         |-- fabric-block-api-v1 1.0.10+92a0d36777
wthit-1  |         |-- fabric-block-view-api-v2 1.0.0+92a0d36777
wthit-1  |         |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
wthit-1  |         |-- fabric-client-tags-api-v1 1.1.1+97bb207577
wthit-1  |         |-- fabric-command-api-v1 1.2.33+f71b366f77
wthit-1  |         |-- fabric-command-api-v2 2.2.12+b3afc78b77
wthit-1  |         |-- fabric-commands-v0 0.2.50+df3654b377
wthit-1  |         |-- fabric-containers-v0 0.1.63+df3654b377
wthit-1  |         |-- fabric-content-registries-v0 4.0.10+57aed33f77
wthit-1  |         |-- fabric-convention-tags-v1 1.5.4+a1a980da77
wthit-1  |         |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
wthit-1  |         |-- fabric-data-generation-api-v1 12.3.2+d7b148e077
wthit-1  |         |-- fabric-dimensions-v1 2.1.53+8536527b77
wthit-1  |         |-- fabric-entity-events-v1 1.5.22+b3afc78b77
wthit-1  |         |-- fabric-events-interaction-v0 0.6.1+e91849a877
wthit-1  |         |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
wthit-1  |         |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
wthit-1  |         |-- fabric-item-api-v1 2.1.27+b3afc78b77
wthit-1  |         |-- fabric-item-group-api-v1 4.0.11+d7b148e077
wthit-1  |         |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
wthit-1  |         |-- fabric-keybindings-v0 0.2.34+df3654b377
wthit-1  |         |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
wthit-1  |         |-- fabric-loot-api-v2 1.2.0+96dfa95977
wthit-1  |         |-- fabric-loot-tables-v1 1.1.44+9e7660c677
wthit-1  |         |-- fabric-message-api-v1 5.1.8+d7b148e077
wthit-1  |         |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
wthit-1  |         |-- fabric-model-loading-api-v1 1.0.2+709a987177
wthit-1  |         |-- fabric-models-v0 0.4.1+9386d8a777
wthit-1  |         |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
wthit-1  |         |-- fabric-networking-v0 0.3.50+df3654b377
wthit-1  |         |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
wthit-1  |         |-- fabric-particles-v1 1.1.1+201a23a077
wthit-1  |         |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
wthit-1  |         |-- fabric-registry-sync-v0 2.3.2+4df89eb277
wthit-1  |         |-- fabric-renderer-api-v1 3.2.0+39a511ba77
wthit-1  |         |-- fabric-renderer-indigo 1.5.0+39a511ba77
wthit-1  |         |-- fabric-renderer-registries-v1 3.2.45+df3654b377
wthit-1  |         |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
wthit-1  |         |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
wthit-1  |         |-- fabric-rendering-v0 1.1.48+df3654b377
wthit-1  |         |-- fabric-rendering-v1 3.0.7+b3afc78b77
wthit-1  |         |-- fabric-resource-conditions-api-v1 2.3.6+d7b148e077
wthit-1  |         |-- fabric-resource-loader-v0 0.11.9+132c48c177
wthit-1  |         |-- fabric-screen-api-v1 2.0.7+b3afc78b77
wthit-1  |         |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
wthit-1  |         |-- fabric-sound-api-v1 1.0.12+b3afc78b77
wthit-1  |         |-- fabric-transfer-api-v1 3.3.2+1bc31aeb77
wthit-1  |         \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
wthit-1  |      - fabricloader 0.14.24
wthit-1  |      - java 17
wthit-1  |      - minecraft 1.20.1
wthit-1  |      - wthit 8.4.2
wthit-1  | [18:18:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
wthit-1  | [18:18:18] [main/INFO]: Compatibility level set to JAVA_16
wthit-1  | [18:18:18] [main/INFO]: Compatibility level set to JAVA_17
wthit-1  | [18:18:25] [main/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaPluginCore
wthit-1  | [18:18:25] [main/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaPluginVanilla
wthit-1  | [18:18:25] [main/ERROR]: Failed to start the minecraft server
wthit-1  | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
wthit-1  |      at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
wthit-1  | Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_4597
wthit-1  |      at mcp.mobius.waila.plugin.vanilla.provider.PlantProvider.<clinit>(PlantProvider.java:23) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.plugin.vanilla.WailaPluginVanilla.register(WailaPluginVanilla.java:153) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.plugin.PluginLoader.register(PluginLoader.java:120) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:98) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:40) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      ... 7 more
wthit-1  | Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4597
wthit-1  |      at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
wthit-1  |      at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
wthit-1  |      at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
wthit-1  |      at mcp.mobius.waila.plugin.vanilla.provider.PlantProvider.<clinit>(PlantProvider.java:23) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.plugin.vanilla.WailaPluginVanilla.register(WailaPluginVanilla.java:153) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.plugin.PluginLoader.register(PluginLoader.java:120) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:98) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:40) ~[wthit-fabric-8.4.2.jar:?]
wthit-1  |      at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
wthit-1  |      ... 7 more
wthit-1  | 2023-11-21T18:18:25.613Z     INFO    mc-server-runner        Done
wthit-1 exited with code 0
```

**Comment by webdo** [comment]
I can confirm that it's not an isolated problem, Had  to rollback the mod version on my server, I get the exact same error.

I'm also using docker with the itzg/minecraft-server image, so I thought it might be related.

Just tried on windows on a brand new server without docker:

` [19:10:23] [main/INFO]: Compatibility level set to JAVA_17
[19:10:29] [main/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaPluginCore
[19:10:29] [main/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaPluginVanilla
[19:10:29] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.24-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_4597
        at mcp.mobius.waila.plugin.vanilla.provider.PlantProvider.<clinit>(PlantProvider.java:23) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.plugin.vanilla.WailaPluginVanilla.register(WailaPluginVanilla.java:153) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.plugin.PluginLoader.register(PluginLoader.java:120) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:98) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:40) ~[wthit-fabric-8.4.2.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4597
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at mcp.mobius.waila.plugin.vanilla.provider.PlantProvider.<clinit>(PlantProvider.java:23) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.plugin.vanilla.WailaPluginVanilla.register(WailaPluginVanilla.java:153) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.plugin.PluginLoader.register(PluginLoader.java:120) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:98) ~[wthit-fabric-8.4.2.jar:?]
        at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:40) ~[wthit-fabric-8.4.2.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
        ... 7 more`
        
        
The only mods installed because required by WTHIT:

- fabric-api-0.90.7+1.20.1.jar
- badpackets-fabric-0.4.3.jar
- wthit-fabric-8.4.2.jar

         
If I remove wthit, server boots normally.
