### ISSUE TITLE
creating instance of plugin chesttracker:wthit

### ISSUE THREAD

**Issue by zc1108aaa** [badasintended/wthit#262]
### Describe the issue

[16:02:52] [Render thread/ERROR]: [WTHIT] Error creating instance of plugin chesttracker:wthit
java.lang.NoSuchMethodError: 'java.util.Map net.minecraft.class_304.fabric_getCategoryMap$fabric-key-binding-api-v1_$md$f80f5e$0()'
	at net.fabricmc.fabric.mixin.client.keybinding.KeyBindingAccessor.fabric_getCategoryMap(KeyBindingAccessor.java) ~[fabric-key-binding-api-v1-1.0.45+80f8cf51ff-80b591a76e4394b0.jar:?]
	at net.fabricmc.fabric.impl.client.keybinding.KeyBindingRegistryImpl.getCategoryMap(KeyBindingRegistryImpl.java:38) ~[fabric-key-binding-api-v1-1.0.45+80f8cf51ff-80b591a76e4394b0.jar:?]
	at net.fabricmc.fabric.impl.client.keybinding.KeyBindingRegistryImpl.addCategory(KeyBindingRegistryImpl.java:42) ~[fabric-key-binding-api-v1-1.0.45+80f8cf51ff-80b591a76e4394b0.jar:?]
	at net.fabricmc.fabric.impl.client.keybinding.KeyBindingRegistryImpl.registerKeyBinding(KeyBindingRegistryImpl.java:68) ~[fabric-key-binding-api-v1-1.0.45+80f8cf51ff-80b591a76e4394b0.jar:?]
	at net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper.registerKeyBinding(KeyBindingHelper.java:51) ~[fabric-key-binding-api-v1-1.0.45+80f8cf51ff-80b591a76e4394b0.jar:?]
	at red.jackf.chesttracker.impl.ChestTracker.<clinit>(ChestTracker.java:60) ~[【辅助-箱子追踪】chesttracker-2.4.2+1.20.6.jar:?]
	at red.jackf.chesttracker.impl.compat.mods.wthit.ChestTrackerWTHITPlugin.<clinit>(ChestTrackerWTHITPlugin.java:14) ~[【辅助-箱子追踪】chesttracker-2.4.2+1.20.6.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
	at mcp.mobius.waila.plugin.PluginInfo.register(PluginInfo.java:71) ~[【显示-这是什么】wthit-fabric-11.1.3.jar:?]
	at mcp.mobius.waila.plugin.PluginLoader.readPluginsJson(PluginLoader.java:129) ~[【显示-这是什么】wthit-fabric-11.1.3.jar:?]
	at mcp.mobius.waila.fabric.FabricPluginLoader.lambda$gatherPlugins$0(FabricPluginLoader.java:31) ~[【显示-这是什么】wthit-fabric-11.1.3.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at mcp.mobius.waila.fabric.FabricPluginLoader.gatherPlugins(FabricPluginLoader.java:31) ~[【显示-这是什么】wthit-fabric-11.1.3.jar:?]
	at mcp.mobius.waila.plugin.PluginLoader.loadPlugins(PluginLoader.java:141) ~[【显示-这是什么】wthit-fabric-11.1.3.jar:?]
	at mcp.mobius.waila.fabric.FabricWaila.onInitialize(FabricWaila.java:44) ~[【显示-这是什么】wthit-fabric-11.1.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(Unknown Source) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) [fabric-loader-0.15.11.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:484) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]

### Log output and crash report

1

**Comment by deirn** [comment]
I need the whole log.
