### ISSUE TITLE
looking at a beacon block causes the game to crash

### ISSUE THREAD

**Issue by StarbombC3Y** [badasintended/wthit#263]
### Describe the issue

As soon as the player places a beacon, the world crashes and can't be re-entered until WTHIT is disabled from loading.

### Log output and crash report

https://gist.github.com/StarbombC3Y/860f0776a49be7536bea46d8e7a549f0

### Additional context

crashes on singleplayer and on LAN

**Comment by sternschnaube** [comment]
Same issue, thanks for reporting. Crash on server.

<details>

```
Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (waila:data_typed)
	at net.minecraft.class_9136.handler$dkk000$fabric-networking-api-v1$encode(class_9136.java:1047) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:518) ~[server-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:?]
	at com.ishland.raknetify.fabric.common.connection.RakNetFabricChannelEventListener.write(RakNetFabricChannelEventListener.java:63) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at com.ishland.raknetify.fabric.common.connection.MultiChannellingPacketCapture.write(MultiChannellingPacketCapture.java:44) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:?]
	at com.ishland.raknetify.fabric.common.connection.RakNetCompressionCompatibilityHandler.write(RakNetCompressionCompatibilityHandler.java:42) ~[raknetify-fabric-0.1.0+alpha.5.123-all.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:342) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:337) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_6880.comp_349()" because "$$0" is null
	at net.minecraft.class_2378$1.method_46774(class_2378.java:181) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378$1.method_10206(class_2378.java:178) ~[server-intermediary.jar:?]
	at net.minecraft.class_2359.method_56158(class_2359.java:25) ~[server-intermediary.jar:?]
	at net.minecraft.class_9135$16.method_56423(class_9135.java:484) ~[server-intermediary.jar:?]
	at net.minecraft.class_9135$16.encode(class_9135.java:471) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$12.encode(class_9139.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$10.encode(class_9139.java:117) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$11.encode(class_9139.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.handler$zeg000$badpackets$encode(class_8710.java:534) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.method_56489(class_8710.java:51) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.method_56490(class_8710.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.class_8710$1.encode(class_8710.java:39) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$8.encode(class_9139.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[server-intermediary.jar:?]
	... 49 more
```

</details>

**Comment by deirn** [comment]
@StarbombC3Y your log has nothing to do with WTHIT. Looks like the same issue as https://github.com/jmb05/nifty-carts/issues/25.

**Comment by sternschnaube** [comment]
Thank you!
