### ISSUE TITLE
Cow in a Jar in Cooking For Blockheads giving error when looking at It

### ISSUE THREAD

**Issue by Cocomere** [badasintended/wthit#270]
### Describe the issue

The item "Cow in a Jar" from the mod "Cooking for Blockheads" gives the following error when I look at it:

> [20:04:47] [Server thread/ERROR]: [WTHIT] Caught unhandled exception : [class mcp.mobius.waila.plugin.textile.provider.FluidStorageProvider$$Lambda$32737/0x00000008044a8ac0
player Cocomere] java.lang.IllegalArgumentException: Cannot convert flowing fluid balm-fabric:milk (net.blay09.mods.balm.fabric.fluid.SimpleMilkFluid@16f75225) into a still fluid.
[20:04:47] [Server thread/ERROR]: [WTHIT] java.lang.IllegalArgumentException: Cannot convert flowing fluid balm-fabric:milk (net.blay09.mods.balm.fabric.fluid.SimpleMilkFluid@16f75225) into a still fluid.
	at net.fabricmc.fabric.impl.transfer.fluid.FluidVariantImpl.of(FluidVariantImpl.java:48)
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:72)
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:61)
	at net.blay09.mods.balm.fabric.fluid.BalmFluidStorage.getResource(BalmFluidStorage.java:57)
	at net.blay09.mods.balm.fabric.fluid.BalmFluidStorage.isResourceBlank(BalmFluidStorage.java:52)
	at mcp.mobius.waila.plugin.textile.provider.FluidStorageProvider.addFluid(FluidStorageProvider.java:74)
	at mcp.mobius.waila.plugin.textile.provider.FluidStorageProvider.lambda$appendData$0(FluidStorageProvider.java:43)
	at mcp.mobius.waila.access.DataWriter.lambda$send$1(DataWriter.java:81)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at mcp.mobius.waila.access.DataWriter.send(DataWriter.java:75)
	at mcp.mobius.waila.network.Packets.lambda$initServer$10(Packets.java:166)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:17818)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

>[20:04:47] [Render thread/INFO]: [System] [CHAT] Error on retrieving data from provider mcp.mobius.waila.plugin.textile.provider.FluidStorageProvider$$Lambda$32737/0x00000008044a8ac0

The display functions as intended, but this appears in my chatlog most times I look at the item.

### Log output and crash report

https://paste.ee/p/J0hw

**Comment by deirn** [comment]
Balm issue. Seems to be fixed on 1.21. https://github.com/TwelveIterationMods/Balm/commit/e9632f1df739d197e8fefc1593d1fec9b8e95e57
