### ISSUE TITLE
Crashed with bbor when trying to join a server: Could not initialize class mcp.mobius.waila.mixed.IMixedService

### ISSUE THREAD

**Issue by Sodium-Aluminate** [badasintended/wthit#277]
### Describe the issue

disable [bbor](https://modrinth.com/mod/bbor), enable wthit -> can normally play.
disable wthit, enable bbor -> can normally play.
enable both -> client crashed when joining server.

### Log output and crash report

https://mclo.gs/4YjzC2c#L504

### Additional context

(don't want use github gist, use mclo.gs instead)

minecraft version: 1.20.1(fabric 0.15.11)
openjdk version: 22

server mod list:
```
create-fabric-0.5.1-f-build.1417+mc1.20.1.jar
fabric-api-0.92.2+1.20.1.jar
fabric-carpet-1.20-1.4.112+v230608.jar
FabricProxy-Lite-2.6.0.jar.disabled
FarmersDelight-1.20.1-2.1.1+refabricated.jar
lithium-fabric-mc1.20.1-0.11.2.jar
NoChatReports-FABRIC-1.20.1-v2.2.2.jar
pca-protocol-1.20-0.2.5.jar
```

client mod list:
```
appleskin-fabric-mc1.20.1-2.5.1
architectury-9.2.14-fabric
badpackets-fabric-0.4.3
baritone-standalone-fabric-1.10.1
BBOutlineReloaded-2.6-1.20.1-fabric
clientcommands-2.8.5
cloth-config-11.1.118-fabric
cmdkeybind-1.6.3-1.20
create-fabric-0.5.1-f-build.1417 mc1.20.1
fabric-api-0.92.2 1.20.1
fabric-carpet-1.20-1.4.112 v230608
FarmersDelight-1.20.1-2.1.1 refabricated
indium-1.0.30 mc1.20.4
itemscroller-fabric-1.20.1-0.20.0
litematica-fabric-1.20.1-0.15.3
magiclib-all-0.7.398 fe2125a-stable
malilib-fabric-1.20.1-0.16.3
MasaGadget-all-3.2.334 08c8f70-stable
nmuk-1.1.1 mc1.20.1
RoughlyEnoughItems-12.1.725-fabric
sodium-fabric-0.5.8 mc1.20.1
tweakeroo-fabric-1.20.1-0.17.1
wthit-fabric-8.13.2
```

**Comment by deirn** [comment]
Try with only WTHIT and BBOR, along with their dependencies.

**Comment by lamya3** [comment]
Same crash `Could not initialize class mcp.mobius.waila.mixed.IMixedService` 
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-07-20 16:41:11
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class mcp.mobius.waila.mixed.IMixedService
	at net.minecraft.class_634.handler$bga000$wthit$onHandleUpdateTags(class_634.java:7728)
	at net.minecraft.class_634.method_11126(class_634.java:1551)
	at net.minecraft.class_2790.method_12001(class_2790.java:35)
	at net.minecraft.class_2790.method_11054(class_2790.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by lamya3** [comment]
After several tests, I guess **`malilib-fabric-1.20.1-0.16.3`** or **`magiclib-all-0.7.398 fe2125a-stable`** + **wthit-fabric-8.13.2** caused that crash.

### Carsh report
[latest.log](https://github.com/user-attachments/files/16319571/latest.log)

### Server mod list:
None; Leaves server

### Client mod list:
```
Fabric Mods: 
		badpackets: Bad Packets 0.4.3
		bbor: BoundingBoxOutlineReloaded 2.6-1.20.1
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		java: OpenJDK 64-Bit Server VM 17
		magiclib: MagicLib 0.8.576+9192507-stable
			magiclib-1_20_1: MagicLib Legacy Compat for 1.20.1 0.8.23+079e864-stable
			magiclib_core: MagicLib Core API 0.8.114+9ceb5c7-stable
			magiclib_malilib_extra: MagicLib Malilib API 0.8.41+079e864-stable
			magiclib_minecraft_api: MagicLib Minecraft API 0.6.59+079e864-stable
		malilib: MaLiLib 0.16.3
		minecraft: Minecraft 1.20.1
		wthit: wthit 8.13.2
```

**Comment by deirn** [comment]
So it doesn't crash with only WTHIT and BBOR?

After some digging, it seems like MagicLib modifies the classpath, so I'm inclined to say it is probably their fault.
I'm not sure why they need to modify the classpath, most likely because of the multi-version thing.

CC: @Hendrix-Shen

**Comment by horeaper** [comment]
On my machine, game crashes when trying to create a single player world. Same error message.
Crashes with: `BBOutlineReloaded-2.6-1.20.1-fabric` + `wthit-fabric-8.13.3`
Not with: `malilib-fabric-1.20.1-0.16.3` + `wthit-fabric-8.13.3`
