### ISSUE TITLE
Weird crash I keep getting from shulker boxes.

### ISSUE THREAD

**Issue by tort-oise** [badasintended/wthit#62]
Sometimes, when I mine a shulker box (on a server) at some oddly specific time, it crashes with this report:

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2480.method_9574(class_2480.java:257)
	at mcp.mobius.waila.overlay.Raycast.getDisplayItem(Raycast.java:111)
	at mcp.mobius.waila.overlay.Tooltip.render(Tooltip.java:226)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)

-- Affected level --
Details:
	All players: 1 total; [class_746['torrtoise'/48419, l='ClientLevel', x=938.70, y=172.00, z=2537.42]]
	Chunk stats: 361, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (925,75,2502), Section: (at 13,11,6 in 57,4,156; chunk contains blocks 912,0,2496 to 927,255,2511), Region: (1,4; contains chunks 32,128 to 63,159, blocks 512,0,2048 to 1023,255,2559)
	Level time: 163326 game time, 39368380 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:467)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bap000$onCrash(class_310.java:10099)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

Yes, I use MultiMC. Yes, I keep getting this error. Yes, I have other mods, one of which provides more crash details. If you want a full list, please ask me. The server is hosted by me and my friends.

**Comment by deirn** [comment]
Open another issue and actually do what the template asks you to do.
