### ISSUE TITLE
How rude. Shulker box crashes, part 2.

### ISSUE THREAD

**Issue by tort-oise** [badasintended/wthit#63]
Description, same as before: I literally cannot describe it more than the fact that, when I destroy a shulker box right after I close the GUI of it, sometimes, it crashes the game, and it indicates as a waila source.

My log, which I've already posted, is:

-- Head --
Thread: Render thread
Stacktrace:
at net.minecraft.class_2480.method_9574(class_2480.java:257)
at mcp.mobius.waila.overlay.Raycast.getDisplayItem(Raycast.java:111)
at mcp.mobius.waila.overlay.Tooltip.render(Tooltip.java:226)
at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)

-- Affected level --
Details:
All players: 1 total; [class_746['torrtoise'/48419, l='ClientLevel', x=938.70, y=172.00, z=2537.42]]
Chunk stats: 361, 225
Level dimension: minecraft:overworld
Level spawn location: World: (925,75,2502), Section: (at 13,11,6 in 57,4,156; chunk contains blocks 912,0,2496 to 927,255,2511), Region: (1,4; contains chunks 32,128 to 63,159, blocks 512,0,2048 to 1023,255,2559)
Level time: 163326 game time, 39368380 day time
Server brand: Paper
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.class_638.method_8538(class_638.java:467)
at net.minecraft.class_310.method_1587(class_310.java:2399)
at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
at net.minecraft.class_310.modify$bap000$onCrash(class_310.java:10099)
at net.minecraft.class_310.method_1514(class_310.java:752)
at net.minecraft.client.main.Main.main(Main.java:217)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
at org.multimc.EntryPoint.listen(EntryPoint.java:143)
at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- End of Log --

I cannot reproduce this, at a steady timestamp. It just... happens, out of nowhere, sometimes, when I'm just randomly playing on a server. I mine shulker boxes perfectly fine, but once in a while, when I'm mining one, the game freezes, crashes, and the log displays an error from waila and the Fabric API.

As for what I expected to happen, well, it's obvious. I expected me to be able to mine shulker boxes without it sometimes crashing, and this is a bug report, for obvious reasons.

For more context: 
Yes, I use MultiMC. 
Yes, I keep getting this error. 
Yes, I have other mods, one of which provides more crash details. 
If you want a full list of my mods, please ask me.
The server I play on while this usually happens is hosted by my friend, that I regularly play on.
I don't get this crash while wthit is outside of my mod folder.

**Comment by tort-oise** [comment]
And yes, I use Megane. But I don't think Megane is what causing this. I just want to be nice.

**Comment by deirn** [comment]
I need the full log, what you provide is only the stacktrace.

**Comment by tort-oise** [comment]
Could you not have said that instead of closing my issue? Jeez.

---- Minecraft Crash Report ----
// Don't do that.

Time: 19/08/2021, 21:13
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2627.method_11317(net.minecraft.class_2487)" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.31)
	at net.minecraft.block.ShulkerBoxBlock.getPickStack(ShulkerBoxBlock:257)
	at mcp.mobius.waila.overlay.Raycast.getDisplayItem(Raycast.java:111)
	at mcp.mobius.waila.overlay.Tooltip.render(Tooltip.java:226)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.client.gui.hud.InGameHud.handler$zfd000$render(InGameHud:1993)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:439)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:1211)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2480.method_9574(class_2480.java:257)
	at mcp.mobius.waila.overlay.Raycast.getDisplayItem(Raycast.java:111)
	at mcp.mobius.waila.overlay.Tooltip.render(Tooltip.java:226)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)

-- Affected level --
Details:
	All players: 1 total; [class_746['torrtoise'/48419, l='ClientLevel', x=938.70, y=172.00, z=2537.42]]
	Chunk stats: 361, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (925,75,2502), Section: (at 13,11,6 in 57,4,156; chunk contains blocks 912,0,2496 to 927,255,2511), Region: (1,4; contains chunks 32,128 to 63,159, blocks 512,0,2048 to 1023,255,2559)
	Level time: 163326 game time, 39368380 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:467)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$bap000$onCrash(class_310.java:10099)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Depixel.zip, Eternity GUI.zip, Shiny Ingot + Glint 1.17.zip, better spyglass, glasses.zip, Eternity Records.zip, animated-axolotls.zip, CTM.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 611955184 bytes (583 MiB) / 3456106496 bytes (3296 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f11
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29497.56
	Virtual memory used (MB): 26306.70
	Swap memory total (MB): 13239.17
	Swap memory used (MB): 405.27
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx5120m
	Fabric Mods: 
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.4.25
		autoreconnect: AutoReconnect 1.3.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterf3: BetterF3 1.1.3
		bettermounthud: Better Mount HUD 1.1.1
		betterpingdisplay: Better Ping Display 1.1
		boostedbrightness: Boosted Brightness 2.1.0
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		clickthrough: ClickThrough 1.17.1-fabric0.36.1-0.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_google_code_gson_gson: gson 2.8.6
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customsplashscreen: Custom Splash Screen 1.1.0
		de_javagl_obj: obj 0.3.0
		deathlog: DeathLog 0.1.3
		durabilityviewer: Giselbaers Durability Viewer 1.17-fabric0.34.9-1.10
		dynamicfps: Dynamic FPS 2.0.3
		easierchests: EasierChests 1.17-fabric0.34.9-1.6.3
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fabricskyboxes: FabricSkyBoxes 0.5.2
		fallingleaves: Falling Leaves 1.7.2+1.17
		figura: Figura 0.0.6
		gbfabrictools: GBfabrictools 1.3.4+1.17
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.8.7-1.17
		lazydfu: LazyDFU 0.1.2
		lessclutter: Less Clutter 1.1.8
		lightoverlay: Light Overlay 6.0.0
		malilib: MaLiLib 0.10.0-dev.24
		megane: megane 5.0.0
		megane-base: megane-base 5.0.0
		megane-runtime: megane-runtime 5.0.0
		megane-vanilla: megane-vanilla 5.0.0+1.17
		midnightlib: MidnightLib 0.2.2
		minecraft: Minecraft 1.17.1
		minecraftcapes: MinecraftCapes Mod 10
		minemenufabric: MineMenuFabric 6.0
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.2
		multiconnect: MultiConnect 1.4.12
		multiconnect-api: MultiConnect API 1.4.12
		notenoughcrashes: Not Enough Crashes 3.4.0+1.17
		optifabric: OptiFabric 1.11.20
		org_luaj_luaj-jse: luaj-jse 3.0.1
		org_yaml_snakeyaml: snakeyaml 1.29
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		roughlyenoughitems: Roughly Enough Items 6.0.268-alpha
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		viafabric: ViaFabric 0.4.3+220-main
		viafabric-mc117: ViaFabric for 1.17 0.4.3+220-main
		viaversion: ViaVersion 4.0.2-SNAPSHOT
		visualoverhaul: VisualOverhaul 3.3.0
		wi_zoom: WI Zoom 1.3-MC1.17.1
		wildfire_gender: Wildfire's Female Gender Mod 2.6.1
		wthit: wthit 3.5.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 2560x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Depixel.zip, file/Eternity GUI.zip, file/Shiny Ingot + Glint 1.17.zip, file/better spyglass, file/glasses.zip, file/Eternity Records.zip, file/animated-axolotls.zip, file/CTM.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.17.1_HD_U_G9_pre34
	OptiFine Build: 20210816-215103
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 3.2.0 NVIDIA 471.11
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	Suspected Mods: wthit (wthit), Fabric Loader (fabricloader), Fabric Rendering (v1) (fabric-rendering-v1)

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_G9_pre34
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/tortoise/Desktop/all the minecraft you can find/MultiMC/instances/1.17.1 men allt gör maximalt ont/.minecraft/.optifine/OptiFine_1.17.1_HD_U_G9_pre34/Optifine-mapped.jar
	OptiFabric error: <None>


I don't have more than this. I'd also like to add that I have had the same issue using Sodium.

**Comment by deirn** [comment]
That's still not the entire log, it's just the crash report but i guess whatever.

> `wthit 3.5.1`

Of course. Of course you use old version because it's [already fucking fixed](https://github.com/badasintended/wthit/tree/3.5.2).

**Comment by tort-oise** [comment]
I apologise.
But, I only have crash reports saved. I don't save my logs, so I couldn't tell you even if I tried. 
My .jar file says wthit is at 3.8.1, so I didn't take that into consideration.

**Comment by tort-oise** [comment]
A tip: Try being nice to people, even if you find them so stupid you want to smash them over the head. 
I'll admit, I'm pretty dumb, but you act as if you're pissed off through this entire issue.
