### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jahirtrap** [badasintended/wthit#77]
### Describe the issue

---- Minecraft Crash Report ----
// My bad.

Time: 2/10/21 19:52
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fmllegacy.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.17.1-37.0.73-universal.jar%2365!:?] {re:classloading}
	at net.minecraftforge.fmlclient.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.17.1-37.0.73-universal.jar%2365!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:361) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:874) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.73.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?] {}
-- MOD waila --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: mcp/mobius/waila/api/ui/IElement
		at java.lang.Class.forName0(Native Method) ~[?:?] {}
		at java.lang.Class.forName(Class.java:375) ~[?:?] {}
		at mcp.mobius.waila.plugin.PluginLoader.createPlugin(PluginLoader.java:20) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
		at mcp.mobius.waila.forge.ForgePluginLoader.lambda$gatherPlugins$0(ForgePluginLoader.java:24) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
		at mcp.mobius.waila.forge.ForgePluginLoader.lambda$gatherPlugins$1(ForgePluginLoader.java:13) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
		at mcp.mobius.waila.forge.ForgePluginLoader.gatherPlugins(ForgePluginLoader.java:13) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
		at mcp.mobius.waila.plugin.PluginLoader.initialize(PluginLoader.java:36) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
		at mcp.mobius.waila.forge.ForgeWaila.loadComplete(ForgeWaila.java:76) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading,pl:eventbus:A}
		at net.minecraftforge.eventbus.ASMEventHandler_7_ForgeWaila_loadComplete_FMLLoadCompleteEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.73.jar%2363!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.73.jar%2362!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: wthit-forge-3.9.2.jar
	Failure message: waila (waila) encountered an error during the complete event phase
		java.lang.NoClassDefFoundError: mcp/mobius/waila/api/ui/IElement
	Mod Version: 3.9.2
	Mod Issue URL: https://github.com/badasintended/wthit/issues
	Exception message: java.lang.ClassNotFoundException: mcp.mobius.waila.api.ui.IElement
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.46.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.46.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:375) ~[?:?] {}
	at mcp.mobius.waila.plugin.PluginLoader.createPlugin(PluginLoader.java:20) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
	at mcp.mobius.waila.forge.ForgePluginLoader.lambda$gatherPlugins$0(ForgePluginLoader.java:24) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at mcp.mobius.waila.forge.ForgePluginLoader.lambda$gatherPlugins$1(ForgePluginLoader.java:13) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at mcp.mobius.waila.forge.ForgePluginLoader.gatherPlugins(ForgePluginLoader.java:13) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
	at mcp.mobius.waila.plugin.PluginLoader.initialize(PluginLoader.java:36) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading}
	at mcp.mobius.waila.forge.ForgeWaila.loadComplete(ForgeWaila.java:76) ~[wthit-forge-3.9.2.jar%2360!:3.9.2] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_7_ForgeWaila_loadComplete_FMLLoadCompleteEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.17.1-37.0.73.jar%2363!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.17.1-37.0.73.jar%2362!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3391303848 bytes (3234 MiB) / 3825205248 bytes (3648 MiB) up to 3825205248 bytes (3648 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1,50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Plus Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x8a52
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9365
	Graphics card #1 name: NVIDIA GeForce MX230
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048,00
	Graphics card #1 deviceId: 0x1d11
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6231
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20503,47
	Virtual memory used (MB): 9484,18
	Swap memory total (MB): 4352,00
	Swap memory used (MB): 33,71
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx3636M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		tombstone-1.17.1-7.2.1.jar                        |Corail Tombstone              |tombstone                     |7.2.1               |DONE      |Manifest: NOSIGNATURE
		wthit-forge-3.9.2.jar                             |wthit                         |wthit                         |3.9.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.73-universal.jar                |Forge                         |forge                         |37.0.73             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: 523492bb-cc93-444b-8206-e58f549c3f7e
	FML: 37.0
	Forge: net.minecraftforge:37.0.73

### Log output

----

**Comment by deirn** [comment]
Honestly, just use jade.
