### ISSUE TITLE
Mob "recipe" crash the game

### ISSUE THREAD

**Issue by Simplebenja** [badasintended/wthit#79]
### Describe the issue

If you try to see the "recipe" of any mob (at least sheep, horses, chickens, squid, iron golems and villagers) using "show recipe" (by default the "4" key, but I am using the "r") the game will crash.
This happens only when JEI is also installed

It is expected to do nothing and not crash I guess.

To play it, just point to any mob and hit the "show recipe" key (4 by default, in my case "r") and the game will crash.

![2021-10-11_00 02 21](https://user-images.githubusercontent.com/92282280/136735854-59f557d4-7248-47cf-86fb-7d2fc5a15979.png)

![2021-10-11_00 03 21](https://user-images.githubusercontent.com/92282280/136735880-4bfd1f5e-eacc-4573-b332-ba3595ff502f.png)

[crash-2021-10-10_23.51.22-client.txt](https://github.com/badasintended/wthit/files/7319623/crash-2021-10-10_23.51.22-client.txt)

### Log output

[10oct.2021 23:46:53.315] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Simplebenja, --version, Forge 1.17.1, --gameDir, C:\Users\Usuario\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Usuario\AppData\Roaming\.minecraft\assets, --assetIndex, 1.17, --uuid, 7f3a27b643b34461a9940ea9b884b02e, --accessToken, ????????, --userType, mojang, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 37.0.78, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038] [10oct.2021 23:46:53.324] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 16.0.1 by Microsoft [10oct.2021 23:46:53.501] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=union:/C:/Users/Usuario/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar%2318! Service=ModLauncher Env=CLIENT [10oct.2021 23:46:56.424] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, Forge 1.17.1, --gameDir, C:\Users\Usuario\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Usuario\AppData\Roaming\.minecraft\assets, --uuid, 7f3a27b643b34461a9940ea9b884b02e, --username, Simplebenja, --assetIndex, 1.17, --accessToken, ????????, --userType, mojang, --versionType, modified, --width, 925, --height, 530] [23:47:07] [Render thread/WARN]: Assets URL 'union:/C:/Users/Usuario/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.17.1-20210706.113038/client-1.17.1-20210706.113038-srg.jar%2361!/assets/.mcassetsroot' uses unexpected schema [23:47:07] [Render thread/WARN]: Assets URL 'union:/C:/Users/Usuario/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.17.1-20210706.113038/client-1.17.1-20210706.113038-srg.jar%2361!/data/.mcassetsroot' uses unexpected schema [10oct.2021 23:47:07.212] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [23:47:08] [Render thread/ERROR]: Failed to verify authentication com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401 	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-2.3.31.jar%2342!:?] 	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:112) ~[authlib-2.3.31.jar%2342!:?] 	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:42) ~[authlib-2.3.31.jar%2342!:?] 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:151) ~[authlib-2.3.31.jar%2342!:?] 	at net.minecraft.client.Minecraft.m_91130_(Minecraft.java:601) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:404) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] 	at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.78.jar%2322!:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401 	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:77) ~[authlib-2.3.31.jar%2342!:?] 	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:47) ~[authlib-2.3.31.jar%2342!:?] 	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:104) ~[authlib-2.3.31.jar%2342!:?] 	... 18 more [23:47:08] [Render thread/INFO]: Setting user: Simplebenja [23:47:08] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT [23:47:10] [modloading-worker-2/INFO]: Forge mod loading, version 37.0.78, for MC 1.17.1 with MCP 20210706.113038 [23:47:10] [modloading-worker-2/INFO]: MinecraftForge v37.0.78 Initialized [10oct.2021 23:47:14.680] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded [23:47:15] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources [10oct.2021 23:47:15.556] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json [10oct.2021 23:47:19.796] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: BETA_OUTDATED Current: 37.0.78 Target: 37.0.84 [23:47:26] [Worker-Main-6/INFO]: Discovered plugin waila:core at mcp.mobius.waila.forge.ForgePlugins.Core [23:47:26] [Worker-Main-6/INFO]: Discovered plugin waila:vanilla at mcp.mobius.waila.forge.ForgePlugins.Vanilla [23:47:26] [Worker-Main-6/INFO]: Registering plugin at mcp.mobius.waila.forge.ForgePlugins.Core [23:47:26] [Worker-Main-6/INFO]: Registering plugin at mcp.mobius.waila.forge.ForgePlugins.Vanilla [23:47:27] [Worker-Main-6/INFO]: Plugin config reloaded [23:47:29] [Render thread/INFO]: OpenAL initialized. [23:47:29] [Render thread/INFO]: Sound engine started [23:47:30] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas [23:47:30] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas [23:47:30] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas [23:47:30] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas [23:47:30] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas [23:47:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas [23:47:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas [23:47:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas [23:47:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas [23:47:33] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas [23:47:33] [Render thread/INFO]: Created: 256x128x0 jei:textures/atlas/gui.png-atlas [23:47:34] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id [23:50:04] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0] [23:50:04] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0] [23:50:04] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498] [23:50:04] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498] [23:50:04] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0] [23:50:04] [Render thread/INFO]: Reloading ResourceManager: Default, wthit-forge-3.9.3.jar, forge-1.17.1-37.0.78-universal.jar, jei-1.17.1-8.1.0.21.jar [23:50:05] [Render thread/INFO]: Loaded 7 recipes [23:50:07] [Render thread/INFO]: Loaded 1137 advancements [23:50:07] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance [23:50:08] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0] [23:50:08] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0] [23:50:08] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498] [23:50:08] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498] [23:50:08] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0] [23:50:08] [Render thread/INFO]: Reloading ResourceManager: Default, wthit-forge-3.9.3.jar, forge-1.17.1-37.0.78-universal.jar, jei-1.17.1-8.1.0.21.jar [23:50:09] [Render thread/INFO]: Loaded 7 recipes [23:50:10] [Render thread/INFO]: Loaded 1137 advancements [23:50:10] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance [10oct.2021 23:50:10.954] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [23:50:10] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1 [23:50:10] [Server thread/INFO]: Generating keypair [23:50:11] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld [23:50:11] [Render thread/INFO]: Preparing spawn area: 0% [23:50:11] [Render thread/INFO]: Preparing spawn area: 0% [23:50:12] [Render thread/INFO]: Preparing spawn area: 0% [23:50:15] [Render thread/INFO]: Preparing spawn area: 0% [23:50:15] [Render thread/INFO]: Preparing spawn area: 0% [23:50:15] [Render thread/INFO]: Preparing spawn area: 0% [23:50:15] [Render thread/INFO]: Preparing spawn area: 0% [23:50:15] [Render thread/INFO]: Preparing spawn area: 0% [23:50:15] [Render thread/INFO]: Preparing spawn area: 0% [23:50:15] [Render thread/INFO]: Preparing spawn area: 0% [23:50:16] [Render thread/INFO]: Preparing spawn area: 10% [23:50:16] [Render thread/INFO]: Preparing spawn area: 24% [23:50:17] [Render thread/INFO]: Preparing spawn area: 43% [23:50:17] [Render thread/INFO]: Preparing spawn area: 68% [23:50:18] [Render thread/INFO]: Preparing spawn area: 72% [23:50:19] [Render thread/INFO]: Preparing spawn area: 75% [23:50:19] [Render thread/INFO]: Preparing spawn area: 79% [23:50:19] [Render thread/INFO]: Preparing spawn area: 83% [23:50:20] [Render thread/INFO]: Preparing spawn area: 85% [23:50:20] [Render thread/INFO]: Preparing spawn area: 88% [23:50:21] [Render thread/INFO]: Preparing spawn area: 90% [23:50:21] [Render thread/INFO]: Preparing spawn area: 92% [23:50:22] [Render thread/INFO]: Preparing spawn area: 98% [23:50:22] [Server thread/INFO]: Plugin config reloaded [23:50:22] [Render thread/INFO]: Time elapsed: 11049 ms [23:50:22] [Server thread/INFO]: Changing view distance to 7, from 10 [23:50:23] [Netty Local Client IO #0/INFO]: Connected to a modded server. [23:50:24] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@60a97e3b [23:50:24] [Server thread/INFO]: Simplebenja[local:E:2f0ae68c] logged in with entity id 292 at (124.66452399593314, 62.0, 131.45022303879756) [23:50:24] [Server thread/INFO]: Simplebenja joined the game [23:50:24] [Server thread/INFO]: Saving and pausing game... [23:50:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld [23:50:25] [Render thread/INFO]: Starting JEI... [23:50:25] [Render thread/INFO]: Building ingredient list... [23:50:25] [Render thread/INFO]: Building ingredient list took 5.409 ms [23:50:25] [Render thread/INFO]: Building ingredient filter... [23:50:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether [23:50:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end [23:50:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2125ms or 42 ticks behind [23:50:25] [Render thread/INFO]: Building ingredient filter took 365.5 ms [23:50:25] [Render thread/INFO]: Building bookmarks... [23:50:25] [Render thread/INFO]: Building bookmarks took 11.92 ms [23:50:25] [Render thread/INFO]: Building recipe registry... [23:50:25] [Render thread/INFO]: Building recipe registry took 62.60 ms [23:50:25] [Render thread/INFO]: Building runtime... [23:50:26] [Render thread/INFO]: Building runtime took 164.6 ms [23:50:26] [Render thread/INFO]: Starting JEI took 1.054 s [23:50:26] [Render thread/INFO]: Received config from the server: {"minecraft:pet.owner":true,"minecraft:override.powder_snow":true,"minecraft:override.infested":true,"minecraft:override.trapped_chest":true} [23:50:26] [Render thread/INFO]: Loaded 7 advancements [10oct.2021 23:51:19.081] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Invalid ingredient found. Parameter Name: focus value Ingredient Info: 1 air minecraft:air 	Index: 1 	Listeners: 		0: NORMAL 		1: ASM: class mcp.mobius.waila.forge.ForgeWailaClient$Subscriber clientTick(Lnet/minecraftforge/event/TickEvent$ClientTickEvent;)V 		2: ASM: net.minecraftforge.common.ForgeInternalHandler@266f992a checkSettings(Lnet/minecraftforge/event/TickEvent$ClientTickEvent;)V 		3: net.minecraftforge.eventbus.EventBus$$Lambda$3956/0x0000000800b07688@65bd41d8 java.lang.IllegalArgumentException: Invalid ingredient found. Parameter Name: focus value Ingredient Info: 1 air minecraft:air 	at TRANSFORMER/jei@8.1.0.21/mezz.jei.util.ErrorUtil.checkIsValidIngredient(ErrorUtil.java:294) 	at TRANSFORMER/jei@8.1.0.21/mezz.jei.gui.Focus.<init>(Focus.java:16) 	at TRANSFORMER/jei@8.1.0.21/mezz.jei.recipes.RecipeManager.createFocus(RecipeManager.java:31) 	at TRANSFORMER/wthit@3.9.3/mcp.mobius.waila.integration.jei.JeiRecipeLookup.lambda$onRuntimeAvailable$1(JeiRecipeLookup.java:34) 	at TRANSFORMER/wthit@3.9.3/mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:83) 	at TRANSFORMER/wthit@3.9.3/mcp.mobius.waila.forge.ForgeWailaClient.access$100(ForgeWailaClient.java:32) 	at TRANSFORMER/wthit@3.9.3/mcp.mobius.waila.forge.ForgeWailaClient$Subscriber.clientTick(ForgeWailaClient.java:85) 	at net.minecraftforge.eventbus.ASMEventHandler_4_Subscriber_clientTick_ClientTickEvent.invoke(.dynamic) 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) 	at TRANSFORMER/forge@37.0.78/net.minecraftforge.fmllegacy.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110) 	at TRANSFORMER/minecraft@1.17.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1728) 	at TRANSFORMER/minecraft@1.17.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1014) 	at TRANSFORMER/minecraft@1.17.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) 	at TRANSFORMER/minecraft@1.17.1/net.minecraft.client.main.Main.main(Main.java:186) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:567) 	at MC-BOOTSTRAP/fmlloader@1.17.1-37.0.78/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) 	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

### Additional context

Launcher: TLauncher 2.82
Java: Version 8 actualization 301 compilation 1.8.0_301-b09
Minecraft 1.17.1
Forge 37.0.84
WTHIT version: wthit-forge-3.9.3
JEI version: jei-1.17.1-8.1.0.21

**Comment by guestds** [comment]
i think its known, but just in case it isnt, the wthit 2.10.10 and forge 36.2.4 versions (1.16.5) seem to have this crash as well

**Comment by deirn** [comment]
> i think its known, but just in case it isnt, the wthit 2.10.10 and forge 36.2.4 versions (1.16.5) seem to have this crash as well

74cbaa7839999178f49b1eb2b918e065220b97ac should fix it in 1.16
